---
- name: setup tomcat
  hosts: all
  become: true
  tasks:
  - name: install java on RedHat
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install java on Debian
    apt:
      name: default-jdk
      state: installed
    when: ansible_os_family == "Debian"

  - name: download tomcat
    get_url: 
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.84/bin/apache-tomcat-8.5.84.tar.gz
      dest: /opt

  - name: extract tomcat
    unarchive:
      src: /opt/apache-tomcat-8.5.84.tar.gz
      dest: /opt
      remote_src: yes

  - name: Change permissions
    file:
      path: /opt/apache-tomcat-8.5.84/bin/startup.sh
      mode: '0755'

  - name: start tomcat service
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.84/bin

      

  
